name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Compile C Program
      run: gcc fcfs.c -o fcfs -Wall -Wextra -Werror

    - name: Run and Validate Test Cases
      run: |
        mkdir -p outputs

        # Test Case 1
        echo -e "3\n0 5\n1 3\n2 8" | ./fcfs > outputs/test1_output.txt
        cat <<EOT > outputs/test1_expected.txt
        PROCESS    ARRIVAL_T    BURST_T    COMPLETE_T    WAITING_T    TURN_AROUND_T
        P0             0          5          5            0            5
        P1             1          3          8            4            7
        P2             2          8         16           6           14
        Average Waiting Time: 3.33
        Average Turnaround Time: 8.67
        EOT
        diff outputs/test1_output.txt outputs/test1_expected.txt || echo "Test 1 Failed" >> outputs/failures.txt

        # Test Case 2
        echo -e "4\n0 2\n2 4\n4 6\n6 8" | ./fcfs > outputs/test2_output.txt
        cat <<EOT > outputs/test2_expected.txt
        PROCESS    ARRIVAL_T    BURST_T    COMPLETE_T    WAITING_T    TURN_AROUND_T
        P0             0          2          2            0            2
        P1             2          4          6            0            4
        P2             4          6         12            2            8
        P3             6          8         20            6           14
        Average Waiting Time: 2.00
        Average Turnaround Time: 7.00
        EOT
        diff outputs/test2_output.txt outputs/test2_expected.txt || echo "Test 2 Failed" >> outputs/failures.txt

        # Test Case 3
        echo -e "2\n0 10\n5 5" | ./fcfs > outputs/test3_output.txt
        cat <<EOT > outputs/test3_expected.txt
        PROCESS    ARRIVAL_T    BURST_T    COMPLETE_T    WAITING_T    TURN_AROUND_T
        P0             0         10         10            0           10
        P1             5          5         15            5           10
        Average Waiting Time: 2.50
        Average Turnaround Time: 10.00
        EOT
        diff outputs/test3_output.txt outputs/test3_expected.txt || echo "Test 3 Failed" >> outputs/failures.txt

        # Report failure if any test failed
        if [ -f outputs/failures.txt ]; then
          echo "Some tests failed. Check the output artifacts for details."
          cat outputs/failures.txt
          exit 1
        fi

    - name: Upload Outputs as Artifacts
      if: failure() # Upload only if tests fail you have reached end bro
      uses: actions/upload-artifact@v4
      with:
        name: fcfs-test-failures
        path: outputs/
