name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Install GCC
    - name: Install GCC
      run: sudo apt-get update && sudo apt-get install -y gcc

    # Step 3: Compile the C program
    - name: Compile FCFS Program
      run: gcc fcfs.c -o fcfs

    # Step 4: Run a test case
    - name: Run Test Case
      run: |
        echo -e "3\n0 5\n1 3\n2 8" | ./fcfs
