name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Compile FCFS Program
      run: gcc fcfs.c -o fcfs -Wall -Wextra -Werror

    - name: Run and Validate Test Cases
      run: |
        mkdir -p outputs

        # Define a reusable function
        run_test() {
          input=$1
          expected=$2
          output_file=$3
          echo -e "$input" | ./fcfs > $output_file
          diff $output_file $expected || echo "$output_file Failed" >> outputs/failures.txt
        }

        # Test Case 1
        run_test "3\n0 5\n1 3\n2 8" outputs/test1_expected.txt outputs/test1_output.txt

        # Test Case 2
        run_test "2\n0 10\n5 5" outputs/test2_expected.txt outputs/test2_output.txt

        # Check for failures
        if [ -f outputs/failures.txt ]; then
          echo "Some tests failed. Check the output artifacts."
          cat outputs/failures.txt
          exit 1
        fi

    - name: Upload Outputs as Artifacts
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: fcfs-test-failures
        path: outputs/
