name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Install dependencies
    - name: Install GCC
      run: sudo apt-get update && sudo apt-get install -y gcc

    # Step 3: Compile the C program
    - name: Compile FCFS Program
      run: |
        gcc fcfs.c -o fcfs -Wall -Wextra -Werror
        ./fcfs --version

    # Step 4: Run and validate test cases
    - name: Run and Validate Test Cases
      run: |
        mkdir -p outputs

        run_test() {
          input="$1"
          expected="$2"
          output_file="$3"

          echo -e "$input" | ./fcfs > "$output_file"

          if ! diff -q "$output_file" "$expected"; then
            echo "❌ $output_file failed!" >> outputs/failures.log
          else
            echo "✅ $output_file passed!"
          fi
        }

        # Test Case 1
        cat <<EOT > outputs/test1_expected.txt
Enter the number of processes: 
Enter arrival and burst time for process 0: 
Enter arrival and burst time for process 1: 
Enter arrival and burst time for process 2: 
	PROCESS	ARRIVAL_T	BURST_T	COMPLETE_T	WAITING_T	TURN_AROUND_T
	-------	---------	-------	----------	---------	--------------
	P0	        0	      5	         5	        0	             5
	P1	        1	      3	         8	        4	             7
	P2	        2	      8	        16	        6	            14

Gantt Chart:
P0	P1	P2	
5	8	16	

Average Waiting Time: 3.33
Average Turnaround Time: 8.67
EOT

        run_test "3\n0 5\n1 3\n2 8" outputs/test1_expected.txt outputs/test1_output.txt

        # Test Case 2
        cat <<EOT > outputs/test2_expected.txt
Enter the number of processes: 
Enter arrival and burst time for process 0: 
Enter arrival and burst time for process 1: 
	PROCESS	ARRIVAL_T	BURST_T	COMPLETE_T	WAITING_T	TURN_AROUND_T
	-------	---------	-------	----------	---------	--------------
	P0	        0	     10	        10	        0	            10
	P1	        5	      5	        15	        5	            10

Gantt Chart:
P0	P1	
10	15	

Average Waiting Time: 2.50
Average Turnaround Time: 10.00
EOT

        run_test "2\n0 10\n5 5" outputs/test2_expected.txt outputs/test2_output.txt

        # Check for failures
        if [ -f outputs/failures.log ]; then
          echo "❌ Some tests failed. Check outputs for more details."
          cat outputs/failures.log
          exit 1
        fi

    # Step 5: Upload outputs if tests fail
    - name: Upload Outputs if Tests Fail
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: fcfs-test-failures
        path: outputs/
